import csv
import io
import secrets
import string
from typing import List, Dict
from sqlalchemy.orm import Session
from app.models.models import VaultEntry
from app.core.security import encrypt_password, decrypt_password

def generate_credential(domain: str) -> Dict[str,str]:
    # Generate username and password
    username = f"user_{secrets.token_hex(4)}@jobhunter.local"
    # or could use profile email, but for auto-create we generate
    alphabet = string.ascii_letters + string.digits + "!@#$%"
    password = "".join(secrets.choice(alphabet) for _ in range(16))
    return {"username": username, "password": password, "domain": domain}

def save_vault_entry(db: Session, domain: str, username: str, password: str) -> VaultEntry:
    enc = encrypt_password(password)
    entry = VaultEntry(domain=domain, username=username, password_enc=enc)
    db.add(entry)
    db.commit()
    db.refresh(entry)
    return entry

def list_vault_entries(db: Session):
    return db.query(VaultEntry).all()

def export_chrome_csv(entries: List[VaultEntry]) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["name","url","username","password"])
    for e in entries:
        pwd = decrypt_password(e.password_enc)
        # Chrome expects url
        url = e.domain if e.domain.startswith("http") else f"https://{e.domain}"
        writer.writerow([e.domain, url, e.username, pwd])
    return output.getvalue()

def export_apple_csv(entries: List[VaultEntry]) -> str:
    # Apple Keychain via CSV: Title, URL, Username, Password, Notes, OTPAuth
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Title","URL","Username","Password","Notes","OTPAuth"])
    for e in entries:
        pwd = decrypt_password(e.password_enc)
        url = e.domain if e.domain.startswith("http") else f"https://{e.domain}"
        writer.writerow([e.domain, url, e.username, pwd, "Generated by JobHunter", ""])
    return output.getvalue()

def delete_all_vault(db: Session):
    db.query(VaultEntry).delete()
    db.commit()
