"""initial multi-tenant schema (v2.0.0)

Revision ID: db63915afc60
Revises: 
Create Date: 2026-09-10 20:47:16.634991
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db63915afc60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Table creation order matters on PostgreSQL, which (unlike SQLite) rejects
    # a foreign key that points at a table that does not exist yet. ``users``
    # is the root of the FK graph and comes first; the jobs <-> resumes cycle
    # is broken by creating ``jobs`` without its resume FK and adding it after
    # ``resumes`` exists (see the end of this function).
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('consents', sa.JSON(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_reason', sa.Text(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('company_info', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('freshness_hours', sa.Integer(), nullable=True),
    sa.Column('applied_with_resume_id', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    # applied_with_resume_id -> resumes.id is added at the end of the upgrade:
    # resumes does not exist yet here, and PostgreSQL validates FK targets at
    # CREATE TABLE time (the jobs <-> resumes cycle is otherwise uncreatable).
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_jobs_user_dedupe')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_jobs_user_status', ['user_id', 'status'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('profile_snapshot', sa.JSON(), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('jd_hash', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('parent_resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('text_snapshot', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['parent_resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    # Close the jobs <-> resumes cycle now that both tables exist. SQLite
    # cannot ADD a constraint in place (batch mode rebuilds the table); the
    # other dialects get a plain ALTER TABLE.
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('jobs', schema=None) as batch_op:
            batch_op.create_foreign_key(
                'fk_jobs_resumes_applied_with_resume_id',
                'resumes', ['applied_with_resume_id'], ['id'])
    else:
        op.create_foreign_key(
            'fk_jobs_resumes_applied_with_resume_id',
            'jobs', 'resumes', ['applied_with_resume_id'], ['id'])

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=320), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_audit_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('email_opt_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_optout_user_email')
    )
    with op.batch_alter_table('email_opt_outs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_opt_outs_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_opt_outs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_opt_outs_user_id'), ['user_id'], unique=False)

    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(), nullable=False),
    sa.Column('to_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('recipient_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tracking_token', sa.String(length=64), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=True),
    sa.Column('opens', sa.Integer(), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_tracking_token'), ['tracking_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_unsubscribe_token'), ['unsubscribe_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_user_id'), ['user_id'], unique=False)

    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pipeline', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_user_id'), ['user_id'], unique=False)

    op.create_table('funding_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('raised_at', sa.DateTime(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords_matched', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('has_open_positions', sa.Boolean(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_funding_user_name')
    )
    with op.batch_alter_table('funding_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funding_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_companies_user_id'), ['user_id'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_user_id'), ['user_id'], unique=False)

    op.create_table('pipeline_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_pipeline_user_dedupe')
    )
    with op.batch_alter_table('pipeline_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_pipeline_jobs_claim', ['pipeline', 'status', 'scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('master_resume_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'key', name='uq_settings_user_cat_key')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=False)

    op.create_table('user_input_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_input_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_input_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_input_requests_user_id'), ['user_id'], unique=False)

    op.create_table('vault_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_enc', sa.String(), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain', name='uq_vault_user_domain')
    )
    with op.batch_alter_table('vault_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_entries_user_id'), ['user_id'], unique=False)

    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_events_email_id'), ['email_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_events_id'))
        batch_op.drop_index(batch_op.f('ix_email_events_email_id'))

    op.drop_table('email_events')
    with op.batch_alter_table('vault_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_vault_entries_id'))

    op.drop_table('vault_entries')
    with op.batch_alter_table('user_input_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_input_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_input_requests_id'))

    op.drop_table('user_input_requests')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))

    op.drop_table('settings')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('pipeline_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_jobs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_jobs_id'))
        batch_op.drop_index('ix_pipeline_jobs_claim')

    op.drop_table('pipeline_jobs')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_events_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('funding_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funding_companies_user_id'))
        batch_op.drop_index(batch_op.f('ix_funding_companies_id'))

    op.drop_table('funding_companies')
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_error_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_error_logs_id'))

    op.drop_table('error_logs')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_user_id'))
        batch_op.drop_index(batch_op.f('ix_emails_unsubscribe_token'))
        batch_op.drop_index(batch_op.f('ix_emails_tracking_token'))
        batch_op.drop_index(batch_op.f('ix_emails_id'))

    op.drop_table('emails')
    with op.batch_alter_table('email_opt_outs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_opt_outs_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_opt_outs_id'))
        batch_op.drop_index(batch_op.f('ix_email_opt_outs_email'))

    op.drop_table('email_opt_outs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))

    op.drop_table('api_keys')
    # Drop order is FK-safe for PostgreSQL (which enforces referential
    # integrity at DROP time). The jobs <-> resumes cycle must be broken
    # before either table goes: both tables reference the other, so a DROP of
    # either is blocked by the *other side's* FK. Dropping the named
    # jobs->resumes constraint unblocks resumes (nothing else references
    # resumes), and once resumes is gone its resumes->jobs FK no longer
    # blocks jobs. SQLite embeds FKs in the table definition, so the
    # DROP TABLE removes them with no constraint to name.
    if op.get_bind().dialect.name != 'sqlite':
        op.drop_constraint(
            'fk_jobs_resumes_applied_with_resume_id', 'jobs', type_='foreignkey')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))
        batch_op.drop_index(batch_op.f('ix_resumes_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_user_status')
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
